update canceled and postponed for event single
mt-support/tribe-ext-events-control pull request #13
Opened 2020-04-24 15:57 UTC by paulmskim

Ticket: https://moderntribe.atlassian.net/browse/EXT-162

2020-04-24 16:54 UTC, jesseeproductions reviewed
Please add a readme entry then all set.

2020-04-24 16:54 UTC, jesseeproductions commented on src/views/single/canceled-status.php
> +	$label = sprintf( _x( 'This %s has been canceled', 'Text to display canceled on event single if no canceled reason.', 'tribe-ext-events-control' ), tribe_get_event_label_singular() );
I was thinking we might not want to include the %s in the translation, but then we have only `This` be a translated string, which makes it harder to translate too. I think we can stick with this.

2020-04-24 17:44 UTC, Camwyn requested changes
Either add a comment as in the suggestions - or better yet, add something to the context string to indicate what the `%s` represents.

2020-04-24 17:44 UTC, Camwyn commented on src/views/single/canceled-status.php
> +	$label = sprintf( _x( 'This %s has been canceled', 'Text to display canceled on event single if no canceled reason.', 'tribe-ext-events-control' ), tribe_get_event_label_singular() );
```suggestion
        /* translators: single event label */
	$label = sprintf( _x( 'This %s has been canceled', 'Text to display canceled on event single if no canceled reason.', 'tribe-ext-events-control' ), tribe_get_event_label_singular() );
```

2020-04-24 17:44 UTC, Camwyn commented on src/views/single/postponed-status.php
> +	$label = sprintf( _x( 'This %s has been postponed', 'Text to display postponed on event single if no postponed reason.', 'tribe-ext-events-control' ), tribe_get_event_label_singular() );
```suggestion
	/* translators: single event label */
	$label = sprintf( _x( 'This %s has been postponed', 'Text to display postponed on event single if no postponed reason.', 'tribe-ext-events-control' ), tribe_get_event_label_singular() );
```

2022-05-05 09:18 UTC, lucatume commented
This PR is outdated and can be closed.

2022-05-05 09:18 UTC, closed without merging